version: "3.9"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  
  app:
    build: .
    restart: always
    environment:
      ENV: prod
      DEBUG: 1  # remove this on prod
      ALLOWED_HOSTS: "*"
      DATABASE_HOST: db
      DATABASE_NAME: app
      DATABASE_USER: app
      DATABASE_PASSWORD: app
    links:
      - db
#      - redis
  migrate:
    build: .
    entrypoint: ["python", "manage.py", "migrate"]
    environment:
      ENV: prod
#       DEBUG: 1
      ALLOWED_HOSTS: "*"
      DATABASE_HOST: db
      DATABASE_NAME: app
      DATABASE_USER: app
      DATABASE_PASSWORD: app
    links:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
#  redis:
#    image: redis
#    restart: always
#    command: --save 60 1 --loglevel warning
#    volumes:
#      - redis_data:/data


volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  pg_data:
    driver: local
#  redis_data:
#    driver: local

